### ISSUE TITLE
coding style for Python

### ISSUE THREAD

**Issue by shimwell** [openmc-dev/openmc#2002]
Could we have a coding style for Python using in OpenMC such as [Black](https://github.com/psf/black)?

We have a clang coding style for the C++ part of the code and a .clang_format as described in the docs [here](https://docs.openmc.org/en/latest/devguide/styleguide.html?highlight=clang) and [here](https://docs.openmc.org/en/latest/devguide/workflow.html?highlight=clang) so this would be a similar situation for the Python side.

Currently a ```flake8``` on the develop branch scan picks up 2635 pep8 typos

```
flake8 . --extend-exclude=vendor --show-source --statistics  --count
```

This could be brought down a bit if we run a code formatter on the code like this
```
black . --exclude=vendor
```
I notice sometimes we use " " and other times we use ' ' quotes so we could use the  ```--skip-string-normalization``` to avoid changing the string quotes if preferred

Then we could also add a github action to automatically keep the code formatted nicely in the future. This one will format the code and commit back to the feature branch and skip the CI

```
name: black

on:
  push:
    paths:
      - '**.py'

defaults:
  run:
    shell: bash

jobs:
  black:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - name: Install black
        run: |
          python -m pip install --upgrade pip
          pip install black
      - name: Run black
        run: |
          black .
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "[skip ci] Apply formatting changes"
```

And finally we could add a [pre-commit](https://pre-commit.com/) file name```.pre-commit-config.yaml``` to allow developers to automatically format prior to committing
```
repos:
  - repo: https://github.com/psf/black
    rev: 22.1.0
    exclude: vendor
    hooks:
      - id: black
```

There is at least one part of the code that I would refactor as a comment before applying these sweeping changes as in the [assembly](https://github.com/openmc-dev/openmc/blob/e807c264364db415652a10231c51d98116a42069/examples/assembly/assembly.py#L84-L92) example we use white space in the code to indicate location of fuel pins. I would make a comment with the pin layout and then let black format the code.

I would be happy to put in PR(s) for these changes or part of these changes if they are welcome?
